version: "3.3"
services:
  db:
    image: "postgres:16"
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=rms
#  db-2:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: test
#      POSTGRES_USER: user1
#      POSTGRES_PASSWORD: password1
#    ports:
#      - "5430:5432"
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data